# Generated by Django 4.2 on 2023-06-21 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='validity',
            field=models.IntegerField(blank=True, help_text='How long this membership plan will valid after the course purchase', null=True),
        ),
    ]
