# Generated by Django 4.2 on 2023-06-23 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0003_remove_subscription_course_subscription_price_and_more'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='subscription_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='memberships.subscriptiontype'),
            preserve_default=False,
        ),
    ]
